version: "3.8"
services:
  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - elk_network

networks:
  elk_network:
    external: true